# Generated by Django 3.1 on 2021-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_shippingadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
