# Generated by Django 3.1 on 2021-02-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210221_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='image',
        ),
    ]
